### ISSUE TITLE
Possible wrong results with h

### ISSUE THREAD

**Issue by luisbrandao** [fsanzl/silabeador#1]
I was playing around with this and found some oddites:

>>> silabeador.syllabify('conhaque')
['con', 'ha', 'que']
it is wrong Because it is portuguese?

>>> silabeador.syllabify('brandy')
['brandy']
google says conhaque == brandy in spanish, so i think this is wrong.

>>> silabeador.syllabify('Rehusar')
['Rehu', 'sar']
Look wrong to me.

**Comment by fsanzl** [comment]
Thanks! At the moment it doesn't support Portuguese syllabification and it is not planned. It has some tolerance for non-Spanish diacritics and syllabification Latin as long as unmarked long syllables are not involved. However, a proper Portuguese spelling would require to recognise code-switching and, most importantly, an implementation of Portuguese syllabification, which is out of scope.

Regarding 'rehusar', it's a tricky one, as 'h' is mute and, therefore, there must be a diphthong according to the standard rules. However, in Castillian Spanish, it would be syllabified as 're-hu-sar' (not due to the 'h' but 're-' being a prefix; the same happens e.g. with 'reutilizar').  I can (hopefully) address this with a couple of regex in exceptions.lst, but I have to assess first the impact on unrelated potential matches (such as 'reino') and some related yet lexicalised to the extent of making them ambiguous,  such as 'reunión' and 'reiterar', to introduce some nuances.

**Comment by fsanzl** [comment]
Solved for re- and pre-

**Comment by fsanzl** [comment]
After looking at the litrature, it should be C+\<h\>+V  in Spanish as well. I'll check it out.

**Comment by fsanzl** [comment]
I've added an argument _h_ to choose whether the behaviour should abide by the orthographic hyphenation (en-he-brar) or the phonetical transcription (e-nhe-brar).
